### PR TITLE
added unix socket support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I'm actually trying to figure out how to use the pip module that's available in the openvswitch source tree, I made some progress reverse engineering it, https://gist.github.com/0x00002152/97317884ad848586eff1cdcf256dd689#gistcomment-3365181

and just found a pretty helpful example that somebody else came up with:

https://mail.openvswitch.org/pipermail/ovs-dev/2018-June/348271.html

long term is a much better approach than using popen this way, just curious if you had ever tried or made any progress in using the native jsonrpc client?

**Comment by ghost** [comment]
Hey, just thought you might like to know, I did manage to get the official ovs module figured out, but fair warning, it's not for the faint of heart and one can reasonably assume that the reason why it's undocumented is because they don't want anybody to shoot themselves in the foot-- it's a very sharp tool. But it sure beats screen-scraping with popen, IMHO but then again, (I've been waiting all of my life to say this) I know a lot about databases and I've seen and worked on far worse and I've worked under more perilous circumstances, it's not that bad. Here's the client that I am writing and have managed to get working, make sure you read the comments: 

https://github.com/0x00002152/python-docker-openvswitch-plugin/blob/master/src/docker_network_plugin_service/ovs_json_rpc_native_client.py

**Comment by iwaseyusuke** [comment]
@0x00002152 Hi, Sorry for the delay response.
Your PR looks good to me. I added some improvements for pylint, then merged as another PR (https://github.com/iwaseyusuke/python-ovs-vsctl/pull/2).

**Comment by iwaseyusuke** [comment]
Also, as you can see, this repo is not maintained actively because I left the OpenFlow-related project a few years ago. If you need to maintain the codes of this repo, feel free to create your own fork.

**Pull request closed without merging**
